version: '3.1'
services:
    api:
        build: api
        ports:
            - 8000:8000
        volumes:
            - ./api:/app
    mongo:
        image: mongo:3.4
        volumes:
        - ./data:/data/db
        ports:
        - 27017:27017   # for debugging purposes only