version: "3.1"

services:
  database:
    build: 
       context: ./database
    image: ddev_db
    environment:
      POSTGRES_USER: gordonuser
      POSTGRES_DB: ddev
    ports:
      - "5432:5432" 
    networks:
      - back-tier
    secrets:
      - postgres_password

  api:
    build:
       context: api
       dockerfile: Dockerfile-def
    image: ddev_api
    environment:
      - HOST=database
      - PORT=5432
      - TIMEOUT=30
    ports:
      - "8080:8080"
    networks:
      - front-tier
      - back-tier
    secrets:
      - postgres_password

secrets:
  postgres_password:
    file: ./devsecrets/postgres_password
    
networks:
  front-tier:
  back-tier: